---
- name: Configure personal work environment on Arch Linux
  hosts: localhost
  become: true
  tasks:
    - name: "Install security tools"
      ansible.builtin.include_tasks:
        file: ./tasks/security.yml

    - name: "Configure sound system"
      ansible.builtin.include_tasks:
        file: ./tasks/audio.yml

    - name: "Install command line tools"
      ansible.builtin.include_tasks:
        file: ./tasks/cli.yml

    - name: "Install communication tools"
      ansible.builtin.include_tasks:
        file: ./tasks/communication.yml

    - name: "Install desktop tools"
      ansible.builtin.include_tasks:
        file: ./tasks/desktop.yml

    - name: "Install documents tools"
      ansible.builtin.include_tasks:
        file: ./tasks/documents.yml

    - name: "Install fonts"
      ansible.builtin.include_tasks:
        file: ./tasks/fonts.yml

    - name: "Install graphic tools"
      ansible.builtin.include_tasks:
        file: ./tasks/graphics.yml

    - name: "Install networking tools"
      ansible.builtin.include_tasks:
        file: ./tasks/networking.yml

    - name: "Install programming tools"
      ansible.builtin.include_tasks:
        file: ./tasks/programming.yml

# vi: set ft=yaml.ansible ts=2 sts=2 sw=2 et
