---
- name: "Ensure that alsa-utils is installed"
  community.general.pacman:
    name: alsa-utils
    state: present

- name: "Ensure that pipewire is installed"
  community.general.pacman:
    name:
      - pipewire
      - pipewire-alsa
      - pipewire-pulse
    state: present

- name: "Ensure that pavucontrol is installed"
  community.general.pacman:
    name: pavucontrol
    state: present

# vi: set ft=yaml.ansible ts=2 sts=2 sw=2 et
