---
- name: "Ensure that Discord is installed"
  community.general.pacman:
    name: discord
    state: present

- name: "Ensure that Signal is installed"
  community.general.pacman:
    name: signal-desktop
    state: present

- name: "Ensure that Telegram is installed"
  community.general.pacman:
    name: telegram-desktop
    state: present

- name: "Ensure that Thunderbird is installed"
  community.general.pacman:
    name:
      - thunderbird
      - systray-x-common
    state: present
